import Head from 'next/head'


function Login() {


    return (
        <>
            <Head>
                <title>Login - WETFLIX</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <h1>login</h1>
            </div>
        </>

    )

}


export default Login;